name: Build x86-64 or arm-64 images pushes
inputs:
  architecture:
    default: 'x86-64'
    description: 'Architecture name to build for.'
  build-args:
    description: 'Build arguments to to use for building image.'
  name:
    description: 'Image name to build.'
    required: true
  password:
    description: 'Password to log in to github registry.'
    required: true
  registry:
    description: 'Registry to use for image upload.'
    required: true
  username:
    description: 'Login to use for authenticating against registry.'
    required: true
steps:
  - run: echo Hello ${{ inputs.architecture }}.
    shell: bash

