name: Build x86-64 or arm-64 images pushes

inputs:
  architecture:
    default: all
    description: Architecture name to build for.
    type: choice
    options:
      - all
      - arm-64
      - x86-64
  build-args:
    description: List of build-time variables.

  cache-key:
    description: |
      An explicit key for restoring and saving the cache. Refer creating a
      cache key.
    default: buildx-layer
  cache-restore-keys:
    description: |
      An ordered list of prefix-matched keys to use for restoring stale cache
      if no cache hit occurred for key.
    default: buildx-layer
  delete-old-images:
    description: Delete old images.
    default: true
  use-cache:
    description: Use cache when building the image.
    default: true

  name:
    description: Image name to build.
    required: true
  tags:
    description: Image tags to use for registering.
  labels:
    description: Image labels to annotate registered image with.

  registry:
    description: Registry to use for image upload.
    required: true
  username:
    description: Login to use for authenticating against registry.
    required: true
  ownername:
    description: |
      Repository owner name. If not set use provided user names instead.
  password:
    description: Password to log into registry.
    required: true

  alternate-registry:
    description: Alternate registry to use for image upload.
  alternate-username:
    description: |
      Login to use for authenticating against alternate registry. If not set
      use mail username.
  alternate-ownername:
    description: |
      Repository owner name. If not set use provided user names instead.
  alternate-password:
    description: |
      Password to log into alternate registry. If not set use main password.

runs:
  using: composite

  steps:
    - if: contains(inputs.delete-old-images, 'true')
      name: Delete old images
      uses: SmartsquareGmbH/delete-old-packages@v0.8.1
      with:
        names: ${{ inputs.name }}
        type: container
        dry-run: true
