name: Build x86-64 or arm-64 images pushes

inputs:
  architecture:
    default: all
    description: Architecture name to build for.
    type: choice
    options:
      - all
      - arm-64
      - x86-64
  build-args:
    description: List of build-time variables.
  no-cache:
    description: Do not use cache when building the image.
    default: false
    type: boolean

  name:
    description: Image name to build.
    required: true
  tags:
    description: Image tags to use for registering.
  labels:
    description: Image labels to annotate registered image with.

  registry:
    description: Registry to use for image upload.
    required: true
  username:
    description: Login to use for authenticating against registry.
    required: true
  password:
    description: Password to log in to github registry.
    required: true

runs:
  using: composite
  steps:
    - if: |
        inputs.architecture == 'all' ||
        inputs.architecture == 'arm-64' &&
        (runner.arch == 'X86' || runner.arch == 'X64') ||
        inputs.architecture == 'x86-64' && runner.arch == 'ARM64'
      name: Set up QEMU for emulating arm architecture on x86 or vice versa.
      uses: docker/setup-qemu-action@v2.1.0

    - if: |
        inputs.architecture == 'all' ||
        inputs.architecture == 'arm-64' &&
        (runner.arch == 'X86' || runner.arch == 'X64') ||
        inputs.architecture == 'x86-64' && runner.arch == 'ARM64'
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1

    - uses: actions/checkout@v3.1.0

    - name: Log in to the Container registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.1.1
      with:
        images: ${{ inputs.registry }}/${{ inputs.name }}
        # NOTE: If not set branch name will be used.
        tags: latest

    - name: Build for ${{ inputs.architecture }} architecture and push image
      uses: docker/build-push-action@v3.2.0
      with:
        build-args: ${{ startsWith(inputs.build-args, '[') && join(fromJSON(inputs.build-args), ' ') || inputs.build-args }}
        context: .
        no-cache: ${{ inputs.no-cache && 'true' || 'false' }}
        # NOTE: Build for arm and x86 architecture with 64 bit.
        platforms: |
          ${{
            inputs.architecture == 'all' &&
            'linux/amd64,linux/arm64' ||
            inputs.architecture == 'arm-64' &&
            'linux/arm64' ||
            inputs.architecture == 'x86-64' &&
            'linux/amd64'
          }}
        tags: ${{ inputs.tags || steps.meta.outputs.tags }}
        labels: ${{ inputs.labels || steps.meta.outputs.labels }}

        pull: true
        push: true
