name: Build x86-64 image and push
inputs:
  name:
    required: true
  password:
    required: true
  registry:
    required: true
  username:
    required: true
steps:
  - name: Set up QEMU for x86 architecture on arm.
    if: ${{ runner.arch == 'ARM64'  }}
    id: qemu-x86_64
    uses: docker/setup-qemu-action@v1
    with:
      image: tonistiigi/binfmt:latest
      platforms: x86_64

  - uses: actions/checkout@v2

  - name: Log in to the Container registry
    uses: docker/login-action@v2
    with:
      registry: ${{ inputs.registry }}
      username: ${{ inputs.username }}
      password: ${{ inputs.password }}

  - name: Extract metadata (tags, labels) for Docker
    id: meta
    uses: docker/metadata-action@v2
    with:
      images: ${{ inputs.registry }}/${{ inputs.name }}
      # NOTE: If not set branch name will be used.
      tags: latest

  - name: Build x86-64 and push image
    uses: docker/build-push-action@v2
    with:
      context: .
      push: true
      tags: ${{ steps.meta.outputs.tags }}-x86-64
      labels: ${{ steps.meta.outputs.labels }}
