name: Build x86-64 or arm-64 images pushes
inputs:
  architecture:
    default: 'all'
    description: 'Architecture name to build for.'
  build-args:
    description: 'Build arguments to to use for building image.'
  name:
    description: 'Image name to build.'
    required: true
  password:
    description: 'Password to log in to github registry.'
    required: true
  registry:
    description: 'Registry to use for image upload.'
    required: true
  username:
    description: 'Login to use for authenticating against registry.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up QEMU for emulating arm architecture on amd or intel.
      if: ${{
        inputs.architecture == 'all' ||
        inputs.architecture == 'arm-64' &&
        (runner.arch == 'X86' || runner.arch == 'X64') ||
        inputs.architecture == 'x86-64' && runner.arch == 'ARM64'
      }}
      uses: docker/setup-qemu-action@v1

    - uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v2
      with:
        images: ${{ inputs.registry }}/${{ inputs.name }}
        # NOTE: If not set branch name will be used.
        tags: latest

    - name: Build for ${{ inputs.architecture }} architecture and push image
      uses: docker/build-push-action@v2
      with:
        build-args: ${{ inputs.build-args }}
        context: .
        # NOTE: Build for arm and x86 architecture with 64 bit.
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
