name: Build x86-64 or arm-64 images pushes
inputs:
  architecture:
    default: 'x86-64'
    description: 'Architecture name to build for.'
  build-args:
    description: 'Build arguments to to use for building image.'
  name:
    description: 'Image name to build.'
    required: true
  password:
    description: 'Password to log in to github registry.'
    required: true
  registry:
    description: 'Registry to use for image upload.'
    required: true
  username:
    description: 'Login to use for authenticating against registry.'
    required: true
steps:
  - name: Set up QEMU for x86 architecture on arm.
    if: ${{ false && inputs.architecture == 'x86-64' && runner.arch == 'ARM64' }}
    id: qemu-x86_64
    uses: docker/setup-qemu-action@v1
    with:
      image: tonistiigi/binfmt:latest
      platforms: x86_64

  - name: Set up QEMU for emulating arm architecture on amd or intel.
    if: ${{ false && inputs.architecture == 'arm-64' && (runner.arch == 'X86' || runner.arch == 'X64') }}
    id: qemu-arm64
    uses: docker/setup-qemu-action@v1
    with:
      image: tonistiigi/binfmt:latest
      platforms: aarch64

  - uses: actions/checkout@v2

  - name: Log in to the Container registry
    uses: docker/login-action@v2
    with:
      registry: ${{ inputs.registry }}
      username: ${{ inputs.username }}
      password: ${{ inputs.password }}

  - name: Extract metadata (tags, labels) for Docker
    id: meta
    uses: docker/metadata-action@v2
    with:
      images: ${{ inputs.registry }}/${{ inputs.name }}
      # NOTE: If not set branch name will be used.
      tags: latest

  - name: Build x86-64 and push image
    if: ${{ inputs.architecture == 'x86-64' }}
    uses: docker/build-push-action@v2
    with:
      context: .
      push: true
      tags: ${{ steps.meta.outputs.tags }}-x86-64
      labels: ${{ steps.meta.outputs.labels }}

  - name: Build arm-64 and push image
    if: ${{ inputs.architecture == 'arm-64' }}
    uses: docker/build-push-action@v2
    with:
      build-args: ${{ inputs.build-args }}
      context: .
      platforms: linux/arm64/v8
      push: true
      tags: ${{ steps.meta.outputs.tags }}-arm-64
      labels: ${{ steps.meta.outputs.labels }}
